# -*- coding: utf-8 -*-
"""abcx.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TwfEWwZH7CWIxRJWsaFD04I2I-eU9hzM

# Example Defs
"""



def a():
  print('from a')

def b():
  print('from b')

def c():
  print('from c')

if __name__ != "__main__":
  print('abcx defs loaded as module.')
else:
  print('abcx run as main')
  a()
  b()
  c()